name: Java CI with Maven (PSB)

env:
  AZURE_WEBAPP_NAME: scf-remote-storage-app
  JAVA_VERSION: '11'
  DISTRIBUTION: 'zulu'

on:
  push:
    branches: [ "main"]

jobs:
  build:

    runs-on: ubuntu-latest
    environment: 'PSB'

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.DISTRIBUTION }}
          cache: 'maven'

      - name: Build with Maven
        run: mvn package

      - name: Azure WebApp
        uses: Azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_PSB }}
          package: '*.war'